djangonautic/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
 path('signup',views.signup_view,name="signup"),
 path('login',views.login_view,name="login"),
 path('logout',views.logout_view,name="logout"),
]

djangonautic/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [


    path('',views.article_list,name= "list"),
    path('<slug:slug>/',views.article_detail,name="details"),

]

djangonautic/djangonautic/urls.py
from django.urls import path,include
from . import views
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('articles/',include('articles.urls')),
    path('about/',views.about),
    path('',views.homepage)

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumb = models.ImageField(default="default.png",blank=True)

    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:20]+"..."

djangonautic/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('articles:list')

    else:
        form = AuthenticationForm()
    return render(request,"accounts/login.html",{'form':form})


def logout_view(request):
    if request.method =="POST":
        logout(request)
        return redirect('accounts:login')

djangonautic/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required(login_url="/accounts/login")
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles})
@login_required(login_url="/accounts/login")
def article_detail(request,slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug = slug)
    return render(request,'articles/article_details.html',{'article':article})

djangonautic/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request,'homepage.html')
    #return HttpResponse('homepage')
def about(request):
    #return HttpResponse('about')
    return render(request,'about.html')

djangonautic/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}


{% block content %}
  <h1>Login</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
  </form>
{% endblock %}

djangonautic/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}


{% block content %}
  <h1>Signup</h1>
  <form class="site-form" action="/accounts/signup" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Signup">
  </form>
{% endblock %}

djangonautic/articles/templates/articles/article_details.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="article-detail">
  <div class="article">
    <img src ="{{article.thumb.url}}" class="img1">
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>
{% endblock %}

djangonautic/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content %}
  <h1>Article list</h1>
  <div class="articles">
    {% for article in articles %}
      <div class="article">
        <h2><a href="{% url 'articles:details' slug=article.slug %}">{{article.title}}</a></h2>
        <p>{{article.snippet}}</p>
        <p>{{article.date}}</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}

djangonautic/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About us</h1>
    <p>we like djnago</p>
  </body>
</html>

djangonautic/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>article_list</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
    <div class="wrapper">
      <h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.png' %}" class="img2"></a></h1>
      <nav>
        <ul>
          <li>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit">Logout</button>

            </form>
          </li>
        </ul>
      </nav>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

djangonautic/templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
  </head>
  <body>
    <h1>this is the homepage</h1>
    <p>welcome to djnago</p>
    <form class="wel-login" action="/accounts/login" method="post">
      {% csrf_token %}

      <input type="submit" value="Login">

    </form>
    <form class="wel-signup" action="/accounts/signup" method="post">
      {% csrf_token %}

      <input type="submit" value="Signup">

    </form>

  </body>
</html>